type Region = Readonly<{
    id: string;
    name: string;
    researchTypes: string;
    googleSearchDomain: string;
}>;

export const regionsDatabase: ReadonlyArray<Region> = [
    {
        id: "us",
        name: "United States",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com",
    },
    {
        id: "uk",
        name: "United Kingdom",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.co.uk",
    },
    {
        id: "ca",
        name: "Canada",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.ca",
    },
    {
        id: "ru",
        name: "Russia",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.ru",
    },
    {
        id: "de",
        name: "Germany",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.de",
    },
    {
        id: "fr",
        name: "France",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.fr",
    },
    {
        id: "es",
        name: "Spain",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.es",
    },
    {
        id: "it",
        name: "Italy",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.it",
    },
    {
        id: "br",
        name: "Brazil",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.br",
    },
    {
        id: "au",
        name: "Australia",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.au",
    },
    {
        id: "ar",
        name: "Argentina",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.ar",
    },
    {
        id: "be",
        name: "Belgium",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.be",
    },
    {
        id: "ch",
        name: "Switzerland",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.ch",
    },
    {
        id: "dk",
        name: "Denmark",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.dk",
    },
    {
        id: "fi",
        name: "Finland",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.fi",
    },
    {
        id: "hk",
        name: "Hong Kong",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.hk",
    },
    {
        id: "ie",
        name: "Ireland",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.ie",
    },
    {
        id: "il",
        name: "Israel",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.il",
    },
    {
        id: "mx",
        name: "Mexico",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.mx",
    },
    {
        id: "nl",
        name: "Netherlands",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.nl",
    },
    {
        id: "no",
        name: "Norway",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.no",
    },
    {
        id: "pl",
        name: "Poland",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.pl",
    },
    {
        id: "se",
        name: "Sweden",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.se",
    },
    {
        id: "sg",
        name: "Singapore",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.sg",
    },
    {
        id: "tr",
        name: "Turkey",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.tr",
    },
    {
        id: "jp",
        name: "Japan",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.co.jp",
    },
    {
        id: "in",
        name: "India",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.co.in",
    },
    {
        id: "hu",
        name: "Hungary",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.hu",
    },
    {
        id: "af",
        name: "Afghanistan",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.af",
    },
    {
        id: "al",
        name: "Albania",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.al",
    },
    {
        id: "dz",
        name: "Algeria",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.dz",
    },
    {
        id: "ao",
        name: "Angola",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.ao",
    },
    {
        id: "am",
        name: "Armenia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.am",
    },
    {
        id: "at",
        name: "Austria",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.at",
    },
    {
        id: "az",
        name: "Azerbaijan",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.az",
    },
    {
        id: "bh",
        name: "Bahrain",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.bh",
    },
    {
        id: "bd",
        name: "Bangladesh",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.bd",
    },
    {
        id: "by",
        name: "Belarus",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.by",
    },
    {
        id: "bz",
        name: "Belize",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.bz",
    },
    {
        id: "bo",
        name: "Bolivia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.bo",
    },
    {
        id: "ba",
        name: "Bosnia and Herzegovina",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.ba",
    },
    {
        id: "bw",
        name: "Botswana",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.bw",
    },
    {
        id: "bn",
        name: "Brunei",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.bn",
    },
    {
        id: "bg",
        name: "Bulgaria",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.bg",
    },
    {
        id: "cv",
        name: "Cabo Verde",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.cv",
    },
    {
        id: "kh",
        name: "Cambodia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.kh",
    },
    {
        id: "cm",
        name: "Cameroon",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.cm",
    },
    {
        id: "cl",
        name: "Chile",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.cl",
    },
    {
        id: "co",
        name: "Colombia",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.co",
    },
    {
        id: "cr",
        name: "Costa Rica",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.cr",
    },
    {
        id: "hr",
        name: "Croatia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.hr",
    },
    {
        id: "cy",
        name: "Cyprus",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.cy",
    },
    {
        id: "cz",
        name: "Czech Republic",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.cz",
    },
    {
        id: "cd",
        name: "Congo",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.cd",
    },
    {
        id: "do",
        name: "Dominican Republic",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.do",
    },
    {
        id: "ec",
        name: "Ecuador",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.ec",
    },
    {
        id: "eg",
        name: "Egypt",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.eg",
    },
    {
        id: "sv",
        name: "El Salvador",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.sv",
    },
    {
        id: "ee",
        name: "Estonia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.ee",
    },
    {
        id: "et",
        name: "Ethiopia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.et",
    },
    {
        id: "ge",
        name: "Georgia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.ge",
    },
    {
        id: "gh",
        name: "Ghana",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.gh",
    },
    {
        id: "gr",
        name: "Greece",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.gr",
    },
    {
        id: "gt",
        name: "Guatemala",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.gt",
    },
    {
        id: "gy",
        name: "Guyana",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.gy",
    },
    {
        id: "ht",
        name: "Haiti",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.ht",
    },
    {
        id: "hn",
        name: "Honduras",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.hn",
    },
    {
        id: "is",
        name: "Iceland",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.is",
    },
    {
        id: "id",
        name: "Indonesia",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.co.id",
    },
    {
        id: "jm",
        name: "Jamaica",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.jm",
    },
    {
        id: "jo",
        name: "Jordan",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.jo",
    },
    {
        id: "kz",
        name: "Kazakhstan",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.kz",
    },
    {
        id: "kw",
        name: "Kuwait",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.kw",
    },
    {
        id: "lv",
        name: "Latvia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.lv",
    },
    {
        id: "lb",
        name: "Lebanon",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.lb",
    },
    {
        id: "lt",
        name: "Lithuania",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.lt",
    },
    {
        id: "lu",
        name: "Luxembourg",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.lu",
    },
    {
        id: "mg",
        name: "Madagascar",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.mg",
    },
    {
        id: "my",
        name: "Malaysia",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.my",
    },
    {
        id: "mt",
        name: "Malta",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.mt",
    },
    {
        id: "mu",
        name: "Mauritius",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.mu",
    },
    {
        id: "md",
        name: "Moldova",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.md",
    },
    {
        id: "mn",
        name: "Mongolia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.mn",
    },
    {
        id: "me",
        name: "Montenegro",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.me",
    },
    {
        id: "ma",
        name: "Morocco",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.ma",
    },
    {
        id: "mz",
        name: "Mozambique",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.mz",
    },
    {
        id: "na",
        name: "Namibia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.na",
    },
    {
        id: "np",
        name: "Nepal",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.np",
    },
    {
        id: "nz",
        name: "New Zealand",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.co.nz",
    },
    {
        id: "ni",
        name: "Nicaragua",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.ni",
    },
    {
        id: "ng",
        name: "Nigeria",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.ng",
    },
    {
        id: "om",
        name: "Oman",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.om",
    },
    {
        id: "py",
        name: "Paraguay",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.py",
    },
    {
        id: "pe",
        name: "Peru",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.pe",
    },
    {
        id: "ph",
        name: "Philippines",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.com.ph",
    },
    {
        id: "pt",
        name: "Portugal",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.pt",
    },
    {
        id: "ro",
        name: "Romania",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.ro",
    },
    {
        id: "sa",
        name: "Saudi Arabia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.sa",
    },
    {
        id: "sn",
        name: "Senegal",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.sn",
    },
    {
        id: "rs",
        name: "Serbia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.rs",
    },
    {
        id: "sk",
        name: "Slovakia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.sk",
    },
    {
        id: "si",
        name: "Slovenia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.si",
    },
    {
        id: "za",
        name: "South Africa",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.co.za",
    },
    {
        id: "kr",
        name: "South Korea",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.kr",
    },
    {
        id: "lk",
        name: "Sri Lanka",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.lk",
    },
    {
        id: "th",
        name: "Thailand",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.th",
    },
    {
        id: "bs",
        name: "Bahamas",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.bs",
    },
    {
        id: "tt",
        name: "Trinidad and Tobago",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.tt",
    },
    {
        id: "tn",
        name: "Tunisia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.tn",
    },
    {
        id: "ua",
        name: "Ukraine",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.ua",
    },
    {
        id: "ae",
        name: "United Arab Emirates",
        researchTypes: "Organic Adwords PLA Keywords",
        googleSearchDomain: "google.ae",
    },
    {
        id: "uy",
        name: "Uruguay",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.uy",
    },
    {
        id: "ve",
        name: "Venezuela",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.ve",
    },
    {
        id: "vn",
        name: "Vietnam",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.vn",
    },
    {
        id: "zm",
        name: "Zambia",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.zm",
    },
    {
        id: "zw",
        name: "Zimbabwe",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.co.zw",
    },
    {
        id: "ly",
        name: "Libya",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.ly",
    },
    {
        id: "mobile-us",
        name: "United States",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.com",
    },
    {
        id: "mobile-uk",
        name: "United Kingdom",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.com",
    },
    {
        id: "mobile-ca",
        name: "Canada",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.ca",
    },
    {
        id: "mobile-de",
        name: "Germany",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.de",
    },
    {
        id: "mobile-fr",
        name: "France",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.fr",
    },
    {
        id: "mobile-es",
        name: "Spain",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.es",
    },
    {
        id: "mobile-it",
        name: "Italy",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.it",
    },
    {
        id: "mobile-br",
        name: "Brazil",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.com.br",
    },
    {
        id: "mobile-au",
        name: "Australia",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.com.au",
    },
    {
        id: "mobile-dk",
        name: "Denmark",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.dk",
    },
    {
        id: "mobile-mx",
        name: "Mexico",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.com.mx",
    },
    {
        id: "mobile-nl",
        name: "Netherlands",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.nl",
    },
    {
        id: "mobile-se",
        name: "Sweden",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.se",
    },
    {
        id: "mobile-tr",
        name: "Turkey",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.com.tr",
    },
    {
        id: "mobile-in",
        name: "India",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.co.in",
    },
    {
        id: "mobile-id",
        name: "Indonesia",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.co.id",
    },
    {
        id: "mobile-il",
        name: "Israel",
        researchTypes: "Organic Adwords",
        googleSearchDomain: "google.co.il",
    },
    {
        id: "pk",
        name: "Pakistan",
        researchTypes: "Organic Adwords Keywords",
        googleSearchDomain: "google.com.pk",
    },
];
